name: mlm_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  chewie: ^1.8.5
  collection: ^1.18.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_lints: ^4.0.0
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  http: ^0.13.1
  http_parser: ^4.0.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  password_strength: ^0.2.0
  path: ^1.9.0
  percent_indicator: ^4.2.3
  pretty_qr_code: ^3.3.0
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  share: ^2.0.4
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  youtube_player_flutter: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/.env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700